Controllers features
mullenlucas/blog-app-ror pull request #5
Opened 2022-12-08 19:37 UTC by mullenlucas

## Implemented features:

- Added RSpec as a gem to your project.
- Created a Request spec file for all your controllers.
- Made checks for:
    - If response status was correct.
    - If a correct template was rendered.
    - If the response body includes correct placeholder text.

2022-12-08 20:27 UTC, Nemwel-Boniface requested changes
## Hello @mullenlucas     :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Good job working on your project so far! :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 20:27 UTC, Nemwel-Boniface commented on spec/requests/posts_spec.rb
>    end
- [x] For some reason, when I run the tests, some of them seem t be failing. Kindly look into why this is the case.

![image](https://user-images.githubusercontent.com/86318284/206553524-6fc57cc4-9ca3-44f5-ae8c-19ec74439f7b.png)

2022-12-08 20:27 UTC, Nemwel-Boniface commented on spec/requests/users_spec.rb
>    end
- [x] For some reason, when I run the tests, some of them seem t be failing. Kindly look into why this is the case.

![image](https://user-images.githubusercontent.com/86318284/206553524-6fc57cc4-9ca3-44f5-ae8c-19ec74439f7b.png)

2022-12-09 02:46 UTC, andersonlebon approved these changes
### Hello @mullenlucas 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is now professional :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------

2022-12-09 05:53 UTC, merged